import "~/styles/globals.css";

import { Inter } from "next/font/google";
import TopNav from "./_components/TopNav";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`font-sans ${inter.variable}`}>
        <div className="flex min-h-screen flex-col gap-4">
          <TopNav />
          <main className="flex w-full grow flex-col px-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
